### ISSUE TITLE
CBZ не створюється корректно для деяких тайтлів

### ISSUE THREAD

**Issue by natashalysakova** [bigchunguspng/manga-in-ua-downloader#1]
При спробі скачати та зберегти CBZ файл для деяких тайтлів, створюється порожній файл без розширення, розміром 0 кб

<img width="854" alt="image" src="https://github.com/user-attachments/assets/91eff353-ee60-462a-86e6-68b8deb5297f">

`miud https://manga.in.ua/mangas/drama/1821-kaguya-sama-wa-kokurasetai.html -c 1 --cbz -p "SHOGUN TEAM"`

Схоже, що тайтл має в собі якийсь недозволений символ, що не дає коректно створити ZIP (cbz) файл

**Comment by natashalysakova** [comment]
Можна додати в CbzDownloadTask

```c#
public string ReplaceInvalidChars(string filename)
{
    return string.Join("_", filename.Split(Path.GetInvalidFileNameChars()));
}
```
та замінити строку 27 на
```c#
var archive = Path.Combine(RootDirectory, ReplaceInvalidChars(Filename));
```
Після цього cbz створюются нормально

**Comment by bigchunguspng** [comment]
Дякую за знахідку і рішення. Виправив, релізнув.

**Comment by natashalysakova** [comment]
дякую
