### ISSUE TITLE
Помилка при скачування декількох глав

### ISSUE THREAD

**Issue by natashalysakova** [bigchunguspng/manga-in-ua-downloader#2]
При скачуванні декількох глав одночасно виникає помилка, яка схожа на ліміт запитиів зі сторони manga-in-ua

<img width="867" alt="image" src="https://github.com/user-attachments/assets/4a8b7a6b-02af-4cc9-a0bf-17954de3aab0">

Можливо, варто скачувати файли в 1 поток, замість декількох, тим самим, зменшити кількість одночасних запитиів і шанс попасти в ліміт

**Comment by bigchunguspng** [comment]
Додав опцію `--slow`, яка збільшує час між запитами, з нею має працювати. Також зробив так щоб такі помилки не крашили прогу і розпочаті завантаження докачувались до кінця.

**Comment by natashalysakova** [comment]
З опцією --slow все одно час від часу вискакує помилка. З того, що я тестила локально допомогло лише качати одночасно 1 главу, тобто чекати до 100% попередню ТА ще між главами робити невелику затримку.
<img width="867" alt="image" src="https://github.com/user-attachments/assets/83366305-c3bb-48b4-b58d-55349ecf5df2">

Ну або в мене зашвидкий інтернет 🤣

**Comment by bigchunguspng** [comment]
Як варіант, можу додати опцію типу --delay з параметром в секундах, щоб задати мінімальну затримку між запитами.

**Comment by natashalysakova** [comment]
Можна спробувати такий варіант, буде зручно підлаштувати під індивідуальні потреби

**Comment by bigchunguspng** [comment]
Доречі оффтоп: "і", "ґ", та інші специфічні букви в терміналі включаються тут:
![21 08 2024 00-18-35](https://github.com/user-attachments/assets/58fb6068-1588-4f65-9672-0dc4d88ec208)

**Comment by natashalysakova** [comment]
Дуже дякую, включила) 
З приводу скачування: `-wait 2` для мене працює ідеально. Закриваю багу)
